

export const currencyToCashInGeo = { 
  "USDTERC20-to-CASHUSD-in-VINN": "usdterc to cash usd in Vinnitsa",
  "USDTERC20-to-CASHUSD-in-DNPR": "usdterc to cash usd in Dnipro",
  "USDTERC20-to-CASHUSD-in-ZHYTO": "usdterc to cash usd in Zhytomyr",
  "USDTERC20-to-CASHUSD-in-ZAP": "usdterc to cash usd in Zaporizhia",
  "USDTERC20-to-CASHUSD-in-IVFR": "usdterc to cash usd in Ivano-Frankivsk",
  "USDTERC20-to-CASHUSD-in-KIEV": "usdterc to cash usd in Kyiv",
  "USDTERC20-to-CASHUSD-in-KVL": "usdterc to cash usd in Kirovohrad",
  "USDTERC20-to-CASHUSD-in-KRVR": "usdterc to cash usd in Kremenchuk",
  "USDTERC20-to-CASHUSD-in-KROP": "usdterc to cash usd in Kropyvnytskyi",
  "USDTERC20-to-CASHUSD-in-LUTSK": "usdterc to cash usd in Lutsk",
  "USDTERC20-to-CASHUSD-in-LVOV": "usdterc to cash usd in Lviv",
  "USDTERC20-to-CASHUSD-in-MYKL": "usdterc to cash usd in Mykolaiv",
  "USDTERC20-to-CASHUSD-in-ODS": "usdterc to cash usd in Odesa",
  "USDTERC20-to-CASHUSD-in-POLT": "usdterc to cash usd in Poltava",
  "USDTERC20-to-CASHUSD-in-RIVNE": "usdterc to cash usd in Rivne",
  "USDTERC20-to-CASHUSD-in-SUMY": "usdterc to cash usd in Sumy",
  "USDTERC20-to-CASHUSD-in-TERNO": "usdterc to cash usd in Ternopil",
  "USDTERC20-to-CASHUSD-in-UZHH": "usdterc to cash usd in Uzhhorod",
  "USDTERC20-to-CASHUSD-in-HRK": "usdterc to cash usd in Kharkiv",
  "USDTERC20-to-CASHUSD-in-HMLN": "usdterc to cash usd in Khmelnytskyi",
  "USDTERC20-to-CASHUSD-in-CHERK": "usdterc to cash usd in Cherkasy",
  "USDTERC20-to-CASHUSD-in-CHRN": "usdterc to cash usd in Chernihiv",
  "USDTERC20-to-CASHUSD-in-CHERN": "usdterc to cash usd in Chernivtsi",
  // EUR exchange rates
  "USDTERC20-to-CASHEUR-in-VINN": "usdterc to cash eur in Vinnitsa",
  "USDTERC20-to-CASHEUR-in-DNPR": "usdterc to cash eur in Dnipro",
  "USDTERC20-to-CASHEUR-in-ZHYTO": "usdterc to cash eur in Zhytomyr",
  "USDTERC20-to-CASHEUR-in-IVFR": "usdterc to cash eur in Ivano-Frankivsk",
  "USDTERC20-to-CASHEUR-in-KIEV": "usdterc to cash eur in Kyiv",
  "USDTERC20-to-CASHEUR-in-KRVR": "usdterc to cash eur in Kremenchuk",
  "USDTERC20-to-CASHEUR-in-KROP": "usdterc to cash eur in Kropyvnytskyi",
  "USDTERC20-to-CASHEUR-in-LUTSK": "usdterc to cash eur in Lutsk",
  "USDTERC20-to-CASHEUR-in-LVOV": "usdterc to cash eur in Lviv",
  "USDTERC20-to-CASHEUR-in-ODS": "usdterc to cash eur in Odesa",
  "USDTERC20-to-CASHEUR-in-POLT": "usdterc to cash eur in Poltava",
  "USDTERC20-to-CASHEUR-in-RIVNE": "usdterc to cash eur in Rivne",
  "USDTERC20-to-CASHEUR-in-HMLN": "usdterc to cash eur in Khmelnytskyi",
  "USDTERC20-to-CASHEUR-in-CHRN": "usdterc to cash eur in Chernihiv",
  "USDTERC20-to-CASHEUR-in-CHERN": "usdterc to cash eur in Chernivtsi",
  "USDTERC20-to-CASHEUR-in-CHERK": "usdterc to cash eur in Cherkasy",
  "USDTERC20-to-CASHEUR-in-HRK": "usdterc to cash eur in Kharkiv",
  "USDTERC20-to-CASHEUR-in-TERNO": "usdterc to cash eur in Ternopil",
  "USDTERC20-to-CASHEUR-in-UZHH": "usdterc to cash eur in Uzhhorod",
  // ETH exchange rates
  "ETH-to-CASHUSD-in-VINN": "eth to cash usd in Vinnitsa",
  "ETH-to-CASHUSD-in-DNPR": "eth to cash usd in Dnipro",
  "ETH-to-CASHUSD-in-ZHYTO": "eth to cash usd in Zhytomyr",
  "ETH-to-CASHUSD-in-ZAP": "eth to cash usd in Zaporizhia",
  "ETH-to-CASHUSD-in-IVFR": "eth to cash usd in Ivano-Frankivsk",
  "ETH-to-CASHUSD-in-KMNSK": "eth to cash usd in Komsomolsk",
  "ETH-to-CASHUSD-in-KIEV": "eth to cash usd in Kyiv",
  "ETH-to-CASHUSD-in-KVL": "eth to cash usd in Kirovohrad",
  "ETH-to-CASHUSD-in-KRMN": "eth to cash usd in Kremenets",
  "ETH-to-CASHUSD-in-KRVR": "eth to cash usd in Kremenchuk",
  "ETH-to-CASHUSD-in-KROP": "eth to cash usd in Kropyvnytskyi",
  "ETH-to-CASHUSD-in-LUTSK": "eth to cash usd in Lutsk",
  "ETH-to-CASHUSD-in-LVOV": "eth to cash usd in Lviv",
  "ETH-to-CASHUSD-in-MYKL": "eth to cash usd in Mykolaiv",
  "ETH-to-CASHUSD-in-ODS": "eth to cash usd in Odesa",
  "ETH-to-CASHUSD-in-POLT": "eth to cash usd in Poltava",
  "ETH-to-CASHUSD-in-RIVNE": "eth to cash usd in Rivne",
  "ETH-to-CASHUSD-in-SUMY": "eth to cash usd in Sumy",
  "ETH-to-CASHUSD-in-TERNO": "eth to cash usd in Ternopil",
  "ETH-to-CASHUSD-in-UZHH": "eth to cash usd in Uzhhorod",
  "ETH-to-CASHUSD-in-HRK": "eth to cash usd in Kharkiv",
  "ETH-to-CASHUSD-in-CHERK": "eth to cash usd in Cherkasy",
  "ETH-to-CASHUSD-in-HMLN": "eth to cash usd in Khmelnytskyi",
  "ETH-to-CASHUSD-in-CHRN": "eth to cash usd in Chernihiv",
  "ETH-to-CASHUSD-in-CHERN": "eth to cash usd in Chernivtsi",
  // Reversed USD to EUR rates
  "CASHUSD-to-USDTERC20-in-VINN": "cash usd to usdterc in Vinnitsa",
  "CASHUSD-to-USDTERC20-in-DNPR": "cash usd to usdterc in Dnipro",
  "CASHUSD-to-USDTERC20-in-ZHYTO": "cash usd to usdterc in Zhytomyr",
  "CASHUSD-to-USDTERC20-in-ZAP": "cash usd to usdterc in Zaporizhia",
  "CASHUSD-to-USDTERC20-in-IVFR": "cash usd to usdterc in Ivano-Frankivsk",
  "CASHUSD-to-USDTERC20-in-KIEV": "cash usd to usdterc in Kyiv",
  "CASHUSD-to-USDTERC20-in-KRVR": "cash usd to usdterc in Kremenchuk",
  "CASHUSD-to-USDTERC20-in-KROP": "cash usd to usdterc in Kropyvnytskyi",
  "CASHUSD-to-USDTERC20-in-LUTSK": "cash usd to usdterc in Lutsk",
  "CASHUSD-to-USDTERC20-in-LVOV": "cash usd to usdterc in Lviv",
  "CASHUSD-to-USDTERC20-in-ODS": "cash usd to usdterc in Odesa",
  "CASHUSD-to-USDTERC20-in-POLT": "cash usd to usdterc in Poltava",
  "CASHUSD-to-ETH-in-POLT": "cash usd to eth in Poltava",
  "CASHUSD-to-ETH-in-RIVNE": "cash usd to eth in Rivne",
  "CASHUSD-to-ETH-in-SUMY": "cash usd to eth in Sumy",
  "CASHUSD-to-ETH-in-TERNO": "cash usd to eth in Ternopil",
  "CASHUSD-to-ETH-in-UZHH": "cash usd to eth in Uzhhorod",
  "CASHUSD-to-ETH-in-HRK": "cash usd to eth in Kharkiv",
  "CASHUSD-to-ETH-in-HMLN": "cash usd to eth in Khmelnytskyi",
  "CASHUSD-to-ETH-in-CHERK": "cash usd to eth in Cherkasy",
  "CASHUSD-to-ETH-in-CHRN": "cash usd to eth in Chernihiv",
  "CASHUSD-to-ETH-in-CHERN": "cash usd to eth in Chernivtsi",
  // BTC exchange rates
  "BTC-to-CASHUSD-in-VINN": "btc to cash usd in Vinnitsa",
  "BTC-to-CASHUSD-in-DNPR": "btc to cash usd in Dnipro",
  "BTC-to-CASHUSD-in-ZHYTO": "btc to cash usd in Zhytomyr",
  "BTC-to-CASHUSD-in-ZAP": "btc to cash usd in Zaporizhia",
  "BTC-to-CASHUSD-in-IVFR": "btc to cash usd in Ivano-Frankivsk",
  "BTC-to-CASHUSD-in-KMNSK": "btc to cash usd in Komsomolsk",
  "BTC-to-CASHUSD-in-KIEV": "btc to cash usd in Kyiv",
  "BTC-to-CASHUSD-in-KVL": "btc to cash usd in Kirovohrad",
  "BTC-to-CASHUSD-in-KRMN": "btc to cash usd in Kremenets",
  "BTC-to-CASHUSD-in-KRVR": "btc to cash usd in Kremenchuk",
  "BTC-to-CASHUSD-in-KROP": "btc to cash usd in Kropyvnytskyi",
  "BTC-to-CASHUSD-in-LUTSK": "btc to cash usd in Lutsk",
  "BTC-to-CASHUSD-in-LVOV": "btc to cash usd in Lviv",
  "BTC-to-CASHUSD-in-MYKL": "btc to cash usd in Mykolaiv",
  "BTC-to-CASHUSD-in-ODS": "btc to cash usd in Odesa",
  "BTC-to-CASHUSD-in-POLT": "btc to cash usd in Poltava",
  "BTC-to-CASHUSD-in-RIVNE": "btc to cash usd in Rivne",
  "BTC-to-CASHUSD-in-SUMY": "btc to cash usd in Sumy",
  "BTC-to-CASHUSD-in-TERNO": "btc to cash usd in Ternopil",
  "BTC-to-CASHUSD-in-UZHH": "btc to cash usd in Uzhhorod",
  "BTC-to-CASHUSD-in-HRK": "btc to cash usd in Kharkiv",
  "BTC-to-CASHUSD-in-CHERK": "btc to cash usd in Cherkasy",
  "BTC-to-CASHUSD-in-HMLN": "btc to cash usd in Khmelnytskyi",
  "BTC-to-CASHUSD-in-CHRN": "btc to cash usd in Chernihiv",
  "BTC-to-CASHUSD-in-CHERN": "btc to cash usd in Chernivtsi",
  // USDTERC20 to CASHEUR
  "USDTERC20-to-CASHEUR-in-DNPR": "usdterc20 to cash eur in Dnipro",
  "USDTERC20-to-CASHEUR-in-ZHYTO": "usdterc20 to cash eur in Zhytomyr",
  "USDTERC20-to-CASHEUR-in-ZAP": "usdterc20 to cash eur in Zaporizhia",
  "USDTERC20-to-CASHEUR-in-IVFR": "usdterc20 to cash eur in Ivano-Frankivsk",
  "USDTERC20-to-CASHEUR-in-KIEV": "usdterc20 to cash eur in Kyiv",
  "USDTERC20-to-CASHEUR-in-KRVR": "usdterc20 to cash eur in Kremenchuk",
  "USDTERC20-to-CASHEUR-in-LUTSK": "usdterc20 to cash eur in Lutsk",
  "USDTERC20-to-CASHEUR-in-LVOV": "usdterc20 to cash eur in Lviv",
  "USDTERC20-to-CASHEUR-in-ODS": "usdterc20 to cash eur in Odesa",
  "USDTERC20-to-CASHEUR-in-HRK": "usdterc20 to cash eur in Kharkiv",
  "USDTERC20-to-CASHEUR-in-CHRN": "usdterc20 to cash eur in Chernihiv",
  "USDTERC20-to-CASHEUR-in-CHERN": "usdterc20 to cash eur in Chernivtsi",
  "USDTERC20-to-CASHEUR-in-HMLN": "usdterc20 to cash eur in Khmelnytskyi",
  "USDTERC20-to-CASHEUR-in-RIVNE": "usdterc20 to cash eur in Rivne",
  "USDTERC20-to-CASHEUR-in-TERNO": "usdterc20 to cash eur in Ternopil",
  "USDTERC20-to-CASHEUR-in-UZHH": "usdterc20 to cash eur in Uzhhorod",
  "CASHUSD-to-BTC-in-VINN": "cash usd to btc in Vinnitsa",
  "CASHUSD-to-BTC-in-DNPR": "cash usd to btc in Dnipro",
  "CASHUSD-to-BTC-in-ZHYTO": "cash usd to btc in Zhytomyr",
  "CASHUSD-to-BTC-in-ZAP": "cash usd to btc in Zaporizhia",
  "CASHUSD-to-BTC-in-IVFR": "cash usd to btc in Ivano-Frankivsk",
  "CASHUSD-to-BTC-in-KIEV": "cash usd to btc in Kyiv",
  "CASHUSD-to-BTC-in-KRVR": "cash usd to btc in Kremenchuk",
  "CASHUSD-to-BTC-in-KROP": "cash usd to btc in Kropyvnytskyi",
  "CASHUSD-to-BTC-in-LUTSK": "cash usd to btc in Lutsk",
  "CASHUSD-to-BTC-in-LVOV": "cash usd to btc in Lviv",
  "CASHUSD-to-BTC-in-ODS": "cash usd to btc in Odesa",
  "CASHUSD-to-BTC-in-POLT": "cash usd to btc in Poltava",
  "CASHUSD-to-BTC-in-RIVNE": "cash usd to btc in Rivne",
  "CASHUSD-to-BTC-in-SUMY": "cash usd to btc in Sumy",
  "CASHUSD-to-BTC-in-TERNO": "cash usd to btc in Ternopil",
  "CASHUSD-to-BTC-in-UZHH": "cash usd to btc in Uzhhorod",
  "CASHUSD-to-BTC-in-HRK": "cash usd to btc in Kharkiv",
  "CASHUSD-to-BTC-in-HMLN": "cash usd to btc in Khmelnytskyi",
  "CASHUSD-to-BTC-in-CHERK": "cash usd to btc in Cherkasy",
  "CASHUSD-to-BTC-in-CHRN": "cash usd to btc in Chernihiv",
  "CASHUSD-to-BTC-in-CHERN": "cash usd to btc in Chernivtsi",
  "USDTERC20-to-CASHUSD-in-VINN": "usdterc20 to cash usd in Vinnitsa",
  "USDTERC20-to-CASHUSD-in-DNPR": "usdterc20 to cash usd in Dnipro",
  "USDTERC20-to-CASHUSD-in-ZAP": "usdterc20 to cash usd in Zaporizhia",
  "USDTERC20-to-CASHUSD-in-IVFR": "usdterc20 to cash usd in Ivano-Frankivsk",
  "USDTERC20-to-CASHUSD-in-ZHYTO": "usdterc20 to cash usd in Zhytomyr",
  "USDTERC20-to-CASHUSD-in-KIEV": "usdterc20 to cash usd in Kyiv",
  "USDTERC20-to-CASHUSD-in-KVL": "usdterc20 to cash usd in Kirovohrad",
  "USDTERC20-to-CASHUSD-in-KRVR": "usdterc20 to cash usd in Kremenchuk",
  "USDTERC20-to-CASHUSD-in-KROP": "usdterc20 to cash usd in Kropyvnytskyi",
  "USDTERC20-to-CASHUSD-in-LUTSK": "usdterc20 to cash usd in Lutsk",
  "USDTERC20-to-CASHUSD-in-LVOV": "usdterc20 to cash usd in Lviv",
  "USDTERC20-to-CASHUSD-in-MKCH": "usdterc20 to cash usd in Mykolaiv",
  "USDTERC20-to-CASHUSD-in-MYKL": "usdterc20 to cash usd in Mykolaiv",
  "USDTERC20-to-CASHUSD-in-ODS": "usdterc20 to cash usd in Odesa",
  "USDTERC20-to-CASHUSD-in-UZHH": "usdterc20 to cash usd in Uzhhorod",
  "USDTERC20-to-CASHUSD-in-TERNO": "usdterc20 to cash usd in Ternopil",
  "USDTERC20-to-CASHUSD-in-HRK": "usdterc20 to cash usd in Kharkiv",
  "USDTERC20-to-CASHUSD-in-SUMY": "usdterc20 to cash usd in Sumy",
  "USDTERC20-to-CASHUSD-in-RIVNE": "usdterc20 to cash usd in Rivne",
  "USDTERC20-to-CASHUSD-in-POLT": "usdterc20 to cash usd in Poltava",
  // USDTERC20 to CASHPAH (Hryvnia, presumably)
  "USDTERC20-to-CASHUAH-in-VINN": "usdterc20 to cash uah in Vinnitsa",
  "USDTERC20-to-CASHUAH-in-DNPR": "usdterc20 to cash uah in Dnipro",
  "USDTERC20-to-CASHUAH-in-ZAP": "usdterc20 to cash uah in Zaporizhia",
  "USDTERC20-to-CASHUAH-in-IVFR": "usdterc20 to cash uah in Ivano-Frankivsk",
  "USDTERC20-to-CASHUAH-in-ZHYTO": "usdterc20 to cash uah in Zhytomyr",
  "USDTERC20-to-CASHUAH-in-KIEV": "usdterc20 to cash uah in Kyiv",
  "USDTERC20-to-CASHUAH-in-KVL": "usdterc20 to cash uah in Kirovohrad",
  "USDTERC20-to-CASHUAH-in-KRVR": "usdterc20 to cash uah in Kremenchuk",
  "USDTERC20-to-CASHUAH-in-KROP": "usdterc20 to cash uah in Kropyvnytskyi",
  "USDTERC20-to-CASHUAH-in-LUTSK": "usdterc20 to cash uah in Lutsk",
  "USDTERC20-to-CASHUAH-in-LVOV": "usdterc20 to cash uah in Lviv",
  "USDTERC20-to-CASHUAH-in-MKCH": "usdterc20 to cash uah in Mykolaiv",
  "USDTERC20-to-CASHUAH-in-MYKL": "usdterc20 to cash uah in Mykolaiv",
  "USDTERC20-to-CASHUAH-in-ODS": "usdterc20 to cash uah in Odesa",
  "USDTERC20-to-CASHUAH-in-UZHH": "usdterc20 to cash uah in Uzhhorod",
  "USDTERC20-to-CASHUAH-in-TERNO": "usdterc20 to cash uah in Ternopil",
  "USDTERC20-to-CASHUAH-in-HRK": "usdterc20 to cash uah in Kharkiv",
  "USDTERC20-to-CASHUAH-in-SUMY": "usdterc20 to cash uah in Sumy",
  "USDTERC20-to-CASHUAH-in-RIVNE": "usdterc20 to cash uah in Rivne",
  "USDTERC20-to-CASHUAH-in-POLT": "usdterc20 to cash uah in Poltava",
  "USDTERC20-to-CASHUAH-in-VINN": "usdterc20 to cash uah in Vinnitsa",
  "USDTERC20-to-CASHUAH-in-DNPR": "usdterc20 to cash uah in Dnipro",
  "USDTERC20-to-CASHUAH-in-ZAP": "usdterc20 to cash uah in Zaporizhia",
  "USDTERC20-to-CASHUAH-in-IVFR": "usdterc20 to cash uah in Ivano-Frankivsk",
  "USDTERC20-to-CASHUAH-in-ZHYTO": "usdterc20 to cash uah in Zhytomyr",
  "USDTERC20-to-CASHUAH-in-KIEV": "usdterc20 to cash uah in Kyiv",
  "USDTERC20-to-CASHUAH-in-KVL": "usdterc20 to cash uah in Kirovohrad",
  "USDTERC20-to-CASHUAH-in-KROP": "usdterc20 to cash uah in Kropyvnytskyi",
  "USDTERC20-to-CASHUAH-in-LUTSK": "usdterc20 to cash uah in Lutsk",
  "USDTERC20-to-CASHUAH-in-LVOV": "usdterc20 to cash uah in Lviv",
  "USDTERC20-to-CASHUAH-in-MKCH": "usdterc20 to cash uah in Mykolaiv",
  "USDTERC20-to-CASHUAH-in-MYKL": "usdterc20 to cash uah in Mykolaiv",
  "USDTERC20-to-CASHUAH-in-ODS": "usdterc20 to cash uah in Odesa",
  "USDTERC20-to-CASHUAH-in-UZHH": "usdterc20 to cash uah in Uzhhorod",
  "USDTERC20-to-CASHUAH-in-TERNO": "usdterc20 to cash uah in Ternopil",
  "USDTERC20-to-CASHUAH-in-HRK": "usdterc20 to cash uah in Kharkiv",
  "USDTERC20-to-CASHUAH-in-SUMY": "usdterc20 to cash uah in Sumy",
  "USDTERC20-to-CASHUAH-in-RIVNE": "usdterc20 to cash uah in Rivne",
  "USDTERC20-to-CASHUAH-in-POLT": "usdterc20 to cash uah in Poltava",
  "CASHEUR-to-USDTTRC20-in-VINN": "cash eur to usdttrc20 in Vinnitsa",
  "CASHEUR-to-USDTTRC20-in-ZHYTO": "cash eur to usdttrc20 in Zhytomyr",
  "CASHEUR-to-USDTTRC20-in-DNPR": "cash eur to usdttrc20 in Dnipro",
  "CASHEUR-to-USDTTRC20-in-ZAP": "cash eur to usdttrc20 in Zaporizhia",
  "CASHEUR-to-USDTTRC20-in-IVFR": "cash eur to usdttrc20 in Ivano-Frankivsk",
  "CASHEUR-to-USDTTRC20-in-KIEV": "cash eur to usdttrc20 in Kyiv",
  "CASHEUR-to-USDTTRC20-in-KRVR": "cash eur to usdttrc20 in Kremenchuk",
  "CASHEUR-to-USDTTRC20-in-KROP": "cash eur to usdttrc20 in Kropyvnytskyi",
  "CASHEUR-to-USDTTRC20-in-LVOV": "cash eur to usdttrc20 in Lviv",
  "CASHEUR-to-USDTTRC20-in-LUTSK": "cash eur to usdttrc20 in Lutsk",
  "CASHEUR-to-USDTTRC20-in-MYKL": "cash eur to usdttrc20 in Mykolaiv",
  "CASHEUR-to-USDTTRC20-in-ODS": "cash eur to usdttrc20 in Odesa",
  "CASHEUR-to-USDTTRC20-in-POLT": "cash eur to usdttrc20 in Poltava",
  "CASHEUR-to-USDTTRC20-in-RIVNE": "cash eur to usdttrc20 in Rivne",
  "CASHEUR-to-USDTTRC20-in-SUMY": "cash eur to usdttrc20 in Sumy",
  "CASHEUR-to-USDTTRC20-in-TERNO": "cash eur to usdttrc20 in Ternopil",
  "CASHEUR-to-USDTTRC20-in-UZHH": "cash eur to usdttrc20 in Uzhhorod",
  "CASHEUR-to-USDTTRC20-in-HRK": "cash eur to usdttrc20 in Kharkiv",
  "CASHEUR-to-USDTTRC20-in-HMLN": "cash eur to usdttrc20 in Khmelnytskyi",
  "CASHEUR-to-USDTTRC20-in-CHERK": "cash eur to usdttrc20 in Cherkasy",
  "CASHEUR-to-USDTTRC20-in-CHRN": "cash eur to usdttrc20 in Chernihiv",
  "CASHEUR-to-USDTTRC20-in-CHERN": "cash eur to usdttrc20 in Chernivtsi",
  // CASHUSD to USDTTRC20
  "CASHUSD-to-USDTTRC20-in-VINN": "cash usd to usdttrc20 in Vinnitsa",
  "CASHUSD-to-USDTTRC20-in-DNPR": "cash usd to usdttrc20 in Dnipro",
  "CASHUSD-to-USDTTRC20-in-ZHYTO": "cash usd to usdttrc20 in Zhytomyr",
  "CASHUSD-to-USDTTRC20-in-ZAP": "cash usd to usdttrc20 in Zaporizhia",
  "CASHUSD-to-USDTTRC20-in-IVFR": "cash usd to usdttrc20 in Ivano-Frankivsk",
  "CASHUSD-to-USDTTRC20-in-KIEV": "cash usd to usdttrc20 in Kyiv",
  "CASHUSD-to-USDTTRC20-in-KRVR": "cash usd to usdttrc20 in Kremenchuk",
  "CASHUSD-to-USDTTRC20-in-KROP": "cash usd to usdttrc20 in Kropyvnytskyi",
  "CASHUSD-to-USDTTRC20-in-LUTSK": "cash usd to usdttrc20 in Lutsk",
  "CASHUSD-to-USDTTRC20-in-LVOV": "cash usd to usdttrc20 in Lviv",
  "CASHUSD-to-USDTTRC20-in-ODS": "cash usd to usdttrc20 in Odesa",
  "CASHUSD-to-USDTTRC20-in-POLT": "cash usd to usdttrc20 in Poltava",
  "CASHUSD-to-USDTTRC20-in-RIVNE": "cash usd to usdttrc20 in Rivne",
  "CASHUSD-to-USDTTRC20-in-SUMY": "cash usd to usdttrc20 in Sumy",
  "CASHUSD-to-USDTTRC20-in-TERNO": "cash usd to usdttrc20 in Ternopil",
  "CASHUSD-to-USDTTRC20-in-UZHH": "cash usd to usdttrc20 in Uzhhorod",
  "CASHUSD-to-USDTTRC20-in-HRK": "cash usd to usdttrc20 in Kharkiv",
  "CASHUSD-to-USDTTRC20-in-HMLN": "cash usd to usdttrc20 in Khmelnytskyi",
  "CASHUSD-to-USDTTRC20-in-CHERK": "cash usd to usdttrc20 in Cherkasy",
  "CASHUSD-to-USDTTRC20-in-CHRN": "cash usd to usdttrc20 in Chernihiv",
  "CASHUSD-to-USDTTRC20-in-CHERN": "cash usd to usdttrc20 in Chernivtsi",
  "CASHEUR-to-USDTERC20-in-VINN": "casheur to usdterc20 in Vinnitsa",
  "CASHEUR-to-USDTERC20-in-ZHYTO": "casheur to usdterc20 in Zhytomyr",
  "CASHEUR-to-USDTERC20-in-DNPR": "casheur to usdterc20 in Dnipro",
  "CASHEUR-to-USDTERC20-in-ZAP": "casheur to usdterc20 in Zaporizhia",
  "CASHEUR-to-USDTERC20-in-IVFR": "casheur to usdterc20 in Ivano-Frankivsk",
  "CASHEUR-to-USDTERC20-in-KIEV": "casheur to usdterc20 in Kyiv",
  "CASHEUR-to-USDTERC20-in-KRVR": "casheur to usdterc20 in Kremenchuk",
  "CASHEUR-to-USDTERC20-in-KROP": "casheur to usdterc20 in Kropyvnytskyi",
  "CASHEUR-to-USDTERC20-in-LVOV": "casheur to usdterc20 in Lviv",
  "CASHEUR-to-USDTERC20-in-LUTSK": "casheur to usdterc20 in Lutsk",
  "CASHEUR-to-USDTERC20-in-MYKL": "casheur to usdterc20 in Mykolaiv",
  "CASHEUR-to-USDTERC20-in-ODS": "casheur to usdterc20 in Odesa",
  "CASHEUR-to-USDTERC20-in-POLT": "casheur to usdterc20 in Poltava",
  "CASHEUR-to-USDTERC20-in-RIVNE": "casheur to usdterc20 in Rivne",
  "CASHEUR-to-USDTERC20-in-SUMY": "casheur to usdterc20 in Sumy",
  "CASHEUR-to-USDTERC20-in-TERNO": "casheur to usdterc20 in Ternopil",
  "CASHEUR-to-USDTERC20-in-UZHH": "casheur to usdterc20 in Uzhhorod",
  "CASHEUR-to-USDTERC20-in-HRK": "casheur to usdterc20 in Kharkiv",
  "CASHEUR-to-USDTERC20-in-HMLN": "casheur to usdterc20 in Khmelnytskyi",
  "CASHEUR-to-USDTERC20-in-CHERK": "casheur to usdterc20 in Cherkasy",
  "CASHEUR-to-USDTERC20-in-CHRN": "casheur to usdterc20 in Chernihiv",
  "CASHEUR-to-USDTERC20-in-CHERN": "casheur to usdterc20 in Chernivtsi",
  "USDTTRC20-to-CASHEUR-in-BER": "usdttrc20 to casheur in Berlin",
  "USDTTRC20-to-CASHEUR-in-MILAN": "usdttrc20 to casheur in Milan",
  "USDTTRC20-to-CASHEUR-in-ROME": "usdttrc20 to casheur in Rome",
  "USDTTRC20-to-CASHEUR-in-FLRNC": "usdttrc20 to casheur in Florence",
  "USDTTRC20-to-CASHEUR-in-DUSS": "usdttrc20 to casheur in Dusseldorf",
  "USDTTRC20-to-CASHEUR-in-KRKW": "usdttrc20 to casheur in Krakow",
  "USDTTRC20-to-CASHEUR-in-PARIS": "usdttrc20 to casheur in Paris",
  "USDTTRC20-to-CASHEUR-in-VILN": "usdttrc20 to casheur in Vilnius",
  "USDTTRC20-to-CASHEUR-in-WARS": "usdttrc20 to casheur in Warsaw",
  "USDTTRC20-to-CASHEUR-in-FRAN": "usdttrc20 to casheur in Frankfurt",
  "USDTTRC20-to-CASHUSD-in-ASTN": "usdttrc20 to cashusd in Astana",
  "USDTTRC20-to-CASHUSD-in-ALM": "usdttrc20 to cashusd in Almaty",
  "USDTTRC20-to-CASHEUR-in-PRAG": "usdttrc20 to casheur in Prague",
  "USDTTRC20-to-CASHEUR-in-BARC": "usdttrc20 to casheur in Barcelona",
  "USDTTRC20-to-CASHEUR-in-ALIC": "usdttrc20 to casheur in Alicante",
    // CASHUAH to USDTTRC20 and USDTERC20
  "CASHUAH-to-USDTTRC20-in-DNPR": "cashuah to usdttrc20 in Dnipro",
  "CASHUAH-to-USDTTRC20-in-VINN": "cashuah to usdttrc20 in Vinnitsa",
  "CASHUAH-to-USDTTRC20-in-ZHYTO": "cashuah to usdttrc20 in Zhytomyr",
  "CASHUAH-to-USDTTRC20-in-ZAP": "cashuah to usdttrc20 in Zaporizhia",
  "CASHUAH-to-USDTTRC20-in-IVFR": "cashuah to usdttrc20 in Ivano-Frankivsk",
  "CASHUAH-to-USDTTRC20-in-KIEV": "cashuah to usdttrc20 in Kyiv",
  "CASHUAH-to-USDTTRC20-in-KRVR": "cashuah to usdttrc20 in Kremenchuk",
  "CASHUAH-to-USDTTRC20-in-KROP": "cashuah to usdttrc20 in Kropyvnytskyi",
  "CASHUAH-to-USDTTRC20-in-LUTSK": "cashuah to usdttrc20 in Lutsk",
  "CASHUAH-to-USDTTRC20-in-LVOV": "cashuah to usdttrc20 in Lviv",
  "CASHUAH-to-USDTTRC20-in-MYKL": "cashuah to usdttrc20 in Mykolaiv",
  "CASHUAH-to-USDTTRC20-in-ODS": "cashuah to usdttrc20 in Odesa",
  "CASHUAH-to-USDTTRC20-in-POLT": "cashuah to usdttrc20 in Poltava",
  "CASHUAH-to-USDTTRC20-in-RIVNE": "cashuah to usdttrc20 in Rivne",
  "CASHUAH-to-USDTTRC20-in-SUMY": "cashuah to usdttrc20 in Sumy",
  "CASHUAH-to-USDTTRC20-in-TERNO": "cashuah to usdttrc20 in Ternopil",
  "CASHUAH-to-USDTTRC20-in-UZHH": "cashuah to usdttrc20 in Uzhhorod",
  "CASHUAH-to-USDTTRC20-in-HRK": "cashuah to usdttrc20 in Kharkiv",
  "CASHUAH-to-USDTTRC20-in-HMLN": "cashuah to usdttrc20 in Khmelnytskyi",
  "CASHUAH-to-USDTTRC20-in-CHERK": "cashuah to usdttrc20 in Cherkasy",
  "CASHUAH-to-USDTTRC20-in-CHRN": "cashuah to usdttrc20 in Chernihiv",
  "CASHUAH-to-USDTTRC20-in-CHERN": "cashuah to usdttrc20 in Chernivtsi",
  "CASHUAH-to-USDTERC20-in-DNPR": "cashuah to usdterc20 in Dnipro",
  "CASHUAH-to-USDTERC20-in-VINN": "cashuah to usdterc20 in Vinnitsa",
  "CASHUAH-to-USDTERC20-in-ZHYTO": "cashuah to usdterc20 in Zhytomyr",
  "CASHUAH-to-USDTERC20-in-ZAP": "cashuah to usdterc20 in Zaporizhia",
  "CASHUAH-to-USDTERC20-in-IVFR": "cashuah to usdterc20 in Ivano-Frankivsk",
  "CASHUAH-to-USDTERC20-in-KIEV": "cashuah to usdterc20 in Kyiv",
  "CASHUAH-to-USDTERC20-in-KRVR": "cashuah to usdterc20 in Kremenchuk",
  "CASHUAH-to-USDTERC20-in-KROP": "cashuah to usdterc20 in Kropyvnytskyi",
  "CASHUAH-to-USDTERC20-in-LUTSK": "cashuah to usdterc20 in Lutsk",
  "CASHUAH-to-USDTERC20-in-LVOV": "cashuah to usdterc20 in Lviv",
  "CASHUAH-to-USDTERC20-in-MYKL": "cashuah to usdterc20 in Mykolaiv",
  "CASHUAH-to-USDTERC20-in-ODS": "cashuah to usdterc20 in Odesa",
  "CASHUAH-to-USDTERC20-in-POLT": "cashuah to usdterc20 in Poltava",
  "CASHUAH-to-USDTERC20-in-RIVNE": "cashuah to usdterc20 in Rivne",
  "CASHUAH-to-USDTERC20-in-SUMY": "cashuah to usdterc20 in Sumy",
  "CASHUAH-to-USDTERC20-in-TERNO": "cashuah to usdterc20 in Ternopil",
  "CASHUAH-to-USDTERC20-in-UZHH": "cashuah to usdterc20 in Uzhhorod",
  "CASHUAH-to-USDTERC20-in-HRK": "cashuah to usdterc20 in Kharkiv",
  "CASHUAH-to-USDTERC20-in-HMLN": "cashuah to usdterc20 in Khmelnytskyi",
  "CASHUAH-to-USDTERC20-in-CHERK": "cashuah to usdterc20 in Cherkasy",
  "CASHUAH-to-USDTERC20-in-CHRN": "cashuah to usdterc20 in Chernihiv",
  "CASHUAH-to-USDTERC20-in-CHERN": "cashuah to usdterc20 in Chernivtsi"
};

export const currencyExchangeMap = {
  "BTC-to-CARDUAH": "BTC to uah card",
  "USDTERC20-to-CARDUAH": "usdterc20 to uah card",
  "ETH-to-CARDUAH": "eth to uah card",
  "USDTTRC20-to-CARDUAH": "usdttrc20 to uah card",
  "BTC-to-MONOBUAH": "btc to uah monobank",
  "ETH-to-MONOBUAH": "eth to uah monobank",
  "USDTTRC20-to-MONOBUAH": "usdttrc20 to uah monobank",
  "USDTERC20-to-MONOBUAH": "usdterc20 to uah monobank",
  "USDTTRC20-to-P24UAH": "usdttrc20 to uah privat24",
  "USDTTRC20-to-CARDEUR": "usdttrc20 to eur card",
  "USDTERC20-to-CARDEUR": "usdterc20 to eur card",
  "USDTTRC20-to-CARDUSD": "usdttrc20 to usd card",
  "BTC-to-CARDUSD": "btc to usd card",
  "ETH-to-CARDUSD": "eth to usd card",
  "USDTERC20-to-CARDUSD": "usdterc20 to usd card",
  "USDTERC20-to-CARDCNY": "usdterc20 to cny card",
  "USDTTRC20-to-CARDCNY": "usdttrc20 to cny card",
  "USDTTRC20-to-CARDTRY": "usdttrc20 to try card",
  "USDTERC20-to-CARDTRY": "usdterc20 to try card",
  "USDTTRC20-to-CARDPLN": "usdttrc20 to pln card",
  "USDTERC20-to-CARDPLN": "usdterc20 to pln card",
  "USDTTRC20-to-WISEEUR": "usdttrc20 to eur wise",
  "USDTERC20-to-WISEEUR": "usdterc20 to eur wise",
  "USDTTRC20-to-WISEUSD": "usdttrc20 to usd wise",
  "USDTERC20-to-WISEUSD": "usdterc20 to usd wise",
  "USDTTRC20-to-REVBEUR": "usdttrc20 to eur revolut",
  "USDTERC20-to-REVBEUR": "usdterc20 to eur revolut",
  "USDTTRC20-to-REVBUSD": "usdttrc20 to usd revolut",
  "USDTERC20-to-REVBUSD": "usdterc20 to usd revolut",
  "CARDUSD-to-USDTTRC20": "usd card to usdttrc20",
  "WISEUSD-to-USDTTRC20": "usd wise to usdttrc20",
  "WISEUSD-to-USDTERC20": "usd wise to usdterc20",
  "WISEEUR-to-USDTERC20": "eur wise to usdterc20",
  "WISEEUR-to-USDTTRC20": "eur wise to usdttrc20",
  "SEPAEUR-to-USDTTRC20": "eur sepa to usdttrc20",
  "SEPAEUR-to-USDTERC20": "eur sepa to usdterc20",
  "CARDUSD-to-USDTERC20": "usd card to usdterc20",
  "USDTTRC20-to-SEPAEUR": "usdttrc20 to eur sepa",
  "USDTTRC20-to-WIREUSD": "usdttrc20 to usd wire",
  "USDTERC20-to-WIREUSD": "usdterc20 to usd wire",
  "USDTERC20-to-SEPAEUR": "usdterc20 to eur sepa",
  "BTC-to-P24UAH": "btc to uah privat24",
  "USDTTRC20-to-PNRUSD": "usdttrc20 to usd pnr",
  "USDTERC20-to-PNRUSD": "usdterc20 to usd pnr",
  "PNRUSD-to-USDTTRC20": "usd pnr to usdttrc20",
  "SKLUSD-to-USDTTRC20": "usd skl to usdttrc20",
  "SKLUSD-to-USDTERC20": "usd skl to usdterc20",
  "PNRUSD-to-USDTERC20": "usd pnr to usdterc20",
  "ETH-to-P24UAH": "eth to uah privat24",
  "USDTERC20-to-P24UAH": "usdterc20 to uah privat24",
  "USDTERC20-to-CARDKZT": "usdterc20 to kzt card",
  "USDTTRC20-to-CARDKZT": "usdttrc20 to kzt card",
  "USDTERC20-to-PPUSD": "usdterc20 to usd paypal",
  "USDTTRC20-to-PPUSD": "usdttrc20 to usd paypal",
  "USDTTRC20-to-SKLUSD": "usdttrc20 to usd skl",
  "USDTERC20-to-SKLUSD": "usdterc20 to usd skl"
};
